import type { LedgerEntry } from './types';

export const DEMO_ENTRIES: LedgerEntry[] = [
  {
    id: 'TX-001',
    date: '2026-07-01',
    type: 'income',
    category: 'Community donations',
    description: 'Opening community contributions',
    amount: 18_500_000,
    reference: 'CAMPAIGN-JUL',
  },
  {
    id: 'TX-002',
    date: '2026-07-03',
    type: 'expense',
    category: 'Food support',
    description: 'Essential food packages for 20 households',
    amount: 6_200_000,
    reference: 'RECEIPT-1001',
  },
  {
    id: 'TX-003',
    date: '2026-07-05',
    type: 'expense',
    category: 'Education',
    description: 'Books and stationery for local students',
    amount: 3_150_000,
    reference: 'RECEIPT-1002',
  },
  {
    id: 'TX-004',
    date: '2026-07-08',
    type: 'income',
    category: 'Local sponsors',
    description: 'Contribution from neighborhood businesses',
    amount: 9_000_000,
    reference: 'SPONSOR-JUL',
  },
  {
    id: 'TX-005',
    date: '2026-07-10',
    type: 'expense',
    category: 'Transport',
    description: 'Delivery and volunteer transport',
    amount: 1_250_000,
    reference: 'RECEIPT-1003',
  },
  {
    id: 'TX-006',
    date: '2026-07-14',
    type: 'expense',
    category: 'Health support',
    description: 'Community first-aid supplies',
    amount: 2_100_000,
    reference: 'RECEIPT-1004',
  },
  {
    id: 'TX-007',
    date: '2026-07-18',
    type: 'income',
    category: 'Fundraising event',
    description: 'Weekend community market',
    amount: 7_400_000,
    reference: 'EVENT-JUL',
  },
  {
    id: 'TX-008',
    date: '2026-07-22',
    type: 'expense',
    category: 'Operations',
    description: 'Printing and event materials',
    amount: 980_000,
    reference: 'RECEIPT-1005',
  },
  {
    id: 'TX-009',
    date: '2026-07-25',
    type: 'expense',
    category: 'Food support',
    description: 'Additional emergency food packages',
    amount: 2_750_000,
    reference: 'RECEIPT-1006',
  },
  {
    id: 'TX-010',
    date: '2026-07-30',
    type: 'expense',
    category: 'Education',
    description: 'Scholarship contribution',
    amount: 4_000_000,
    reference: 'SCHOLARSHIP-01',
  },
];
